horizon/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('detalhesproduto/<int:id>',views.detalhesproduto),
    path('cart',views.cart),
    path('cadproduto',views.cadproduto),
    path('cadcor',views.cadcor),
    path('cadcategoria',views.cadcategoria),
    path('cadclientes',views.cadclientes),
    path('editacliente',views.editacliente),
    path('cart/<int:id>',views.cart),
    path('exibecarrinho',views.exibecarrinho),
    path('deletaitemdocarrinho/<int:id>',views.deletaitemdocarrinho),
    path('acrescentaitemcarrinho/<int:id>',views.acrescentaitemcarrinho),
    path('subtraiitemcarrinho/<int:id>',views.subtraiitemcarrinho),
    path('subtotal',views.subtotal),
    path('vendafinalizada',views.vendafinalizada),
    path('loja/<int:id>',views.loja),
    path('listadedesejos/<int:id>',views.listadedesejos),
    path('exibelistadedesejos',views.exibelistadedesejos),
    path('removelistadedesejos/<int:id>',views.removelistadedesejos),
]

horizon/horizon/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerce.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

horizon/ecommerce/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.forms.widgets import SelectDateWidget

class Produtos(models.Model):
    nome = models.CharField(max_length=255,null=False,blank=False)
    preco = models.FloatField(null=False,blank=False)
    preco_desconto = models.FloatField(null=True,blank=True)
    percentual_desconto = models.IntegerField()
    categoria = models.ForeignKey('Categorias',on_delete=models.CASCADE)
    descricao = models.TextField(null=True)
    especificacoes = models.TextField(null=False,blank=True)
    quantidade_estoque = models.IntegerField(null=False,blank=False)
    quantidade_vendida = models.IntegerField(blank=True,null=True)
    cor = models.ManyToManyField('Cores')
    imagem = models.ImageField(null=False,blank=False, upload_to="images/")   
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.nome

class Cores (models.Model):
    class Meta:
        ordering = ['cor']
    
    cor = models.CharField(max_length=255,blank=False,null=False,unique=True)

    def __str__(self) -> str:
        return self.cor

class Categorias (models.Model):
    class Meta:
        ordering = ['categoria']
    
    categoria = models.CharField(max_length=255,blank=False,null=False,unique=True)

    def __str__(self) -> str:
        return self.categoria
    
class Clientes (models.Model):

    STATUS = (
        ('m','Masculino'),
        ('m','Feminino'),
        ('outros','Outros')
    )

    usuario = models.ForeignKey(get_user_model(),on_delete = models.CASCADE)
    #nome = models.CharField(max_length=255,blank=False,null=False)
    endereco = models.CharField(max_length=255,blank=False,null=False)
    numero = models.IntegerField()
    complemento = models.CharField(max_length=255,null=False)
    cidade = models.CharField(max_length=55,null=False)
    estado = models.CharField(max_length=55,null=False)
    cep = models.CharField(max_length=8,blank=False,null=False)
    telefone = models.CharField(max_length=11,blank=False,null=False)
    cpf = models.CharField(max_length=11,blank=False,null=False)
    rg = models.CharField(max_length=9,blank=False,null=False)
    sexo = models.CharField(max_length=1,choices=STATUS)
    idade = models.IntegerField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.usuario.first_name

class Carrinho (models.Model):
    cliente = models.ForeignKey('Clientes',on_delete=models.CASCADE)    
    produto = models.ForeignKey('Produtos',on_delete=models.CASCADE)
    quantidade = models.IntegerField()
    cor = models.ForeignKey('Cores',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.cliente.id) + ' - ' + str(self.produto.id)   

class ListaDeDesejos(models.Model):
    cliente = models.ForeignKey('Clientes',on_delete=models.CASCADE)
    produto = models.ForeignKey('Produtos',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.cliente.id) + ' - ' + str(self.produto.id)   

horizon/ecommerce/forms.py
from django import forms
from django.forms import fields, widgets
from django.utils.translation import ugettext_lazy as _
from .models import Produtos, Categorias, Cores, Clientes

class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produtos
        fields = {'nome','preco','percentual_desconto','descricao','especificacoes','quantidade_estoque','categoria','cor','imagem'}


class CorForm(forms.ModelForm):
    class Meta:
        model = Cores
        fields = {'cor'}

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categorias
        fields = {'categoria'}

class ClientesForm (forms.ModelForm):
    class Meta:
        model = Clientes
        fields = {'endereco','numero','complemento','cidade','estado','cep','telefone','cpf','rg','sexo','idade'}

        labels = {
            'endereco': _('Endereço',),
            'numero': _('Número'),
            'cep': _('CEP'),
            'cpf': _('CPF'),
            'rg': _('RG'),
        }


class ClientesSubtotalForm (forms.ModelForm):
    class Meta:
        model = Clientes
        fields = {'endereco','numero','complemento','cidade','estado','cep','telefone'}

        labels = {
            'endereco': _('Endereço',),
            'numero': _('Número'),
            'cep': _('CEP'),
            'cpf': _('CPF'),
            'rg': _('RG'),
        }

horizon/ecommerce/views.py
from typing import Tuple
from django.shortcuts import redirect, render, get_object_or_404
from .models import Produtos,Clientes,Categorias,Cores,Carrinho,ListaDeDesejos
from .forms import ProdutoForm,CorForm,CategoriaForm,ClientesForm,ClientesSubtotalForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
import datetime

#========================================================
#==== PÁGINA INICIAL ====================================
#========================================================

#Página inicial
def home(request):
    lancamentos = Produtos.objects.all().order_by('-created_at')[:5]
    categorias = Categorias.objects.all().order_by('categoria')
    produtos_vendidos = Produtos.objects.filter(quantidade_vendida__gt = 0).order_by('-quantidade_vendida')

    if request.user.is_authenticated == True:
        #pega o id do cliente e verifica se há um cliente cadastrado com esse id, caso não haja ele encaminha para o cadastro de cliente
        cliente = Clientes.objects.filter(usuario = request.user.id).first()
        if cliente == None:
            return redirect('/cadclientes')

        carrinho = Carrinho.objects.filter(cliente = cliente.id)
    else:
        carrinho = ''
    return render(request,'ecommerce/index.html',{'lancamentos':lancamentos,'carrinho':carrinho,'categorias':categorias,'produtos_vendidos':produtos_vendidos})


#========================================================
#==== LOJA ==============================================
#========================================================

#view para acessar a loja com todos os produtos de determinada categoria
def loja(request,id):
    categorias = Categorias.objects.all().order_by('categoria')
    categoria_a_ser_buscada = get_object_or_404(Categorias,pk=id)
    produtos = Produtos.objects.filter(categoria = categoria_a_ser_buscada.id)

    return render(request,'ecommerce/loja.html',{'categorias':categorias,'produtos':produtos,'categoria_a_ser_buscada':categoria_a_ser_buscada})   


#view onde exibe os detalhes do produto
def detalhesproduto(request,id):
    produto = get_object_or_404(Produtos,pk=id)
    return render(request,'ecommerce/detalhesproduto.html',{'produto':produto})

#========================================================
#==== LISTA DE DESEJOS ==================================
#========================================================

@login_required
def listadedesejos(request,id):
    produto = get_object_or_404(Produtos,pk=id)
    cliente = get_object_or_404(Clientes,usuario = request.user.id)

    check = ListaDeDesejos.objects.filter(produto=produto,cliente=cliente)
    print(len(check))
    
    if len(check) == 0:
        ListaDeDesejos.objects.create(produto=produto,cliente=cliente)
        return redirect('/exibelistadedesejos')
    #inserir um return para a página do produto e exibir uma mensagem informando que ele foi salvo na lista de desejos
    return redirect('/exibelistadedesejos')

@login_required
def exibelistadedesejos(request):
    cliente = get_object_or_404(Clientes,usuario = request.user.id)
    lista = ListaDeDesejos.objects.filter(cliente = cliente.id)
    
    if len(lista) == 0:
        vazio = True
    else:
        vazio = False

    return render(request,'ecommerce/exibelistadedesejos.html',{'lista':lista,'vazio':vazio})

@login_required
def removelistadedesejos(request,id):
    desejo = get_object_or_404(ListaDeDesejos,pk=id)
    desejo.delete()
    return redirect('/exibelistadedesejos')

#========================================================
#==== CARRINHO ==========================================
#========================================================

#view para cadastrar os itens do carrinho
@login_required
def cart(request,id):
    cor= get_object_or_404(Cores,pk=request.GET.get('cor'))
    quantidade = request.GET.get('quantidade')
    cli = get_object_or_404(Clientes,usuario = request.user.id)
    prod = get_object_or_404(Produtos,pk=id)
    Carrinho.objects.create(cliente=cli,produto=prod,quantidade=quantidade,cor=cor)
    
    #itens = Carrinho.objects.filter(cliente = cli.id)
    return redirect('/exibecarrinho')#render(request,'ecommerce/exibecarrinho.html')


#view para exibir o carrinho
@login_required
def exibecarrinho(request):
    cli = get_object_or_404(Clientes,usuario = request.user.id)
    #itens do carrinho
    carrinho = Carrinho.objects.filter(cliente = cli.id)
    
    #operação para gerar os produtos, quantidades e valores atualizados
    produtos = []
    total = 0
    for item in carrinho:
        #lê cada um dos itens e salva em uma lista
        obj = []
        obj.append(item.quantidade)
        obj.append(item.produto.nome)
        obj.append(item.quantidade * item.produto.preco)
        #grava a lista com os itens em uma outra lista
        produtos.append(obj)
        #calcula os totais 
        total += (item.quantidade * item.produto.preco)   
    
    if len(carrinho) == 0:
        vazio = True    
    else:
        vazio = False
        
    return render(request,'ecommerce/cart.html',{'carrinho':carrinho,'produtos':produtos,'total':total,'vazio':vazio})

@login_required
def deletaitemdocarrinho(request,id):
    #deleta item do carrinho
    produto_do_carrinho = get_object_or_404(Carrinho,pk=id)
    produto_do_carrinho.delete()
    return redirect('/exibecarrinho')

@login_required
def acrescentaitemcarrinho(request,id):
    acrescenta_item = get_object_or_404(Carrinho,pk=id)
    acrescenta_item.quantidade += 1
    acrescenta_item.save()
    return redirect('/exibecarrinho')
    
@login_required
def subtraiitemcarrinho(request,id):
    subtrai_item = get_object_or_404(Carrinho,pk=id)
    if subtrai_item.quantidade > 1:
        subtrai_item.quantidade -= 1
        subtrai_item.save()
    return redirect('/exibecarrinho')

@login_required
#Subtotal e finalização da venda
def subtotal(request):
    #busca os itens no banco
    cli = get_object_or_404(Clientes,usuario=request.user)
    carrinho = Carrinho.objects.filter(cliente = cli.id)
    #cria o formulario
    form = ClientesSubtotalForm(instance=cli)

    #operação para gerar os produtos, quantidades e valores atualizados
    produtos = []
    total = 0
    for item in carrinho:
        #lê cada um dos itens e salva em uma lista
        obj = []
        obj.append(item.quantidade)
        obj.append(item.produto.nome)
        obj.append(item.quantidade * item.produto.preco)
        #grava a lista com os itens em uma outra lista
        produtos.append(obj)
        #calcula os totais 
        total += (item.quantidade * item.produto.preco) 
    
    #Verifica se a requisição é um POST
    if request.method == 'POST':
        #armazena os dados da requisição em um formulario instanciando o objeto produto
        form = ClientesSubtotalForm(request.POST,instance=cli)
        #Veridica se o formulario é valido
        if form.is_valid():
            #salva o cliente
            cli = form.save()            
            #passa por cada item do carrinho atualizando a quantidade vendida em cada um deles
            for item in carrinho:
                if item.produto.quantidade_vendida != None:
                    item.produto.quantidade_vendida += item.quantidade
                else:
                    item.produto.quantidade_vendida = item.quantidade
                #salva as modificações no produto
                item.produto.save()
            #Apaga os itens do carrinho
            carrinho.delete()

            return redirect('/vendafinalizada')
    return render(request,'ecommerce/subtotal.html',{'form':form,'cli':cli,'carrinho':carrinho,'produtos':produtos,'total':total})

#tela de venda finalizada
@login_required
def vendafinalizada(request):
    return render(request,'ecommerce/vendafinalizada.html')

#========================================================
#==== CADASTRO DE PRODUTOS ==============================
#========================================================

#view para cadastrar produtos
@login_required
def cadproduto(request):
    if request.method == 'POST':
        #pega as informações do POST e a imagem e salva na form
        form = ProdutoForm(request.POST,request.FILES)
        if form.is_valid():
            produto = form.save()
            produto.preco_desconto = produto.preco - ((produto.preco/100) * produto.percentual_desconto)
            if produto.preco_desconto <= 0:
                produto.preco_desconto = produto.preco
                produto.percentual_desconto = 0
            produto.save()
            return redirect('/')
    #manda o formulario de produto para o template
    form = ProdutoForm()
    return render(request,'ecommerce/cadproduto.html',{'form':form})


#view para cadastrar a cor 
@login_required
def cadcor(request):
    if request.method == 'POST':
        form = CorForm(request.POST)

        if form.is_valid():
            cores = form.save(commit=False)
            if cores.cor.isnumeric():
                return redirect('/cadcor')
            else:
                cores.cor = cores.cor.capitalize()
                cores.save()
                return redirect('/cadproduto')
    form = CorForm()
    return render(request,'ecommerce/cadcor.html',{'form':form})


#view para cadastrar a categoria
@login_required
def cadcategoria (request):
    if request.method == 'POST':
        form = CategoriaForm(request.POST)
        if form.is_valid():
            categ = form.save(commit=False)
            
            categ.categoria = categ.categoria.capitalize()
            categ.save()
            return redirect('/cadproduto')

    form = CategoriaForm()
    return render(request,'ecommerce/cadcategoria.html',{'form':form})

#========================================================
#==== CADASTRO DE CLIENTES ==============================
#========================================================

#view para cadastro de cliente
def cadclientes (request):

horizon/ecommerce/templates/ecommerce/cadcategoria.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Cadastro de Categorias{% endblock %}

{% block content %}
<div class="col-md-6 container">
<form method="POST">
    {% csrf_token %}

    {{form.categoria | bootstrap}}

    <input type="submit" class="btn btn-success" value="Enviar">
</form>
</div>
{% endblock %}

horizon/ecommerce/templates/ecommerce/cadclientes.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Dados do Cliente{% endblock %}

{% block content %}
<div class="col-md-8 container">
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label  " for="nome">Nome</label>
        <div class=" ">
            <input type="text" name="nome" maxlength="255" class=" form-control" required="" id="id_nome">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label  " for="sobrenome">Sobrenome</label>
        <div class=" ">
            <input type="text" name="sobrenome" maxlength="255" class=" form-control" required="" id="id_sobrenome">
        </div>
    </div>
    {{form.endereco | bootstrap}}
    {{form.numero | bootstrap}}
    {{form.complemento | bootstrap}}
    {{form.cidade | bootstrap}}
    {{form.estado | bootstrap}}
    {{form.cep | bootstrap}}
    {{form.telefone | bootstrap}}
    {{form.rg | bootstrap}}
    {{form.cpf | bootstrap}}
    {{form.sexo | bootstrap}}
    {{form.idade | bootstrap}}
  

    <input type="submit" class="btn btn-success" value="Enviar">
</form>
</div>
{% endblock %}

horizon/ecommerce/templates/ecommerce/cadcor.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Cadastro de Cores{% endblock %}

{% block content %}
<div class="col-md-6 container-fluid">
    <form method="POST">
        {% csrf_token %}

        {{form.cor | bootstrap}}
        
        <input type="submit" class="btn btn-success" value="Enviar">
    </form>
</div>
{% endblock %}

horizon/ecommerce/templates/ecommerce/cadproduto.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Inserir Novo Produto{% endblock %}

{% block content %}
<div class="col-md-8 container">
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
 
    {{form.categoria | bootstrap}}
    <a href="/cadcategoria"><i class="fas fa-plus corsucesso"> </i> Adicionar nova Categoria <br><br></a>
    {{form.cor | bootstrap}}
    <a href="/cadcor"><i class="fas fa-plus corsucesso"> </i> Adicionar uma nova cor <br><br></a>
    {{form.nome | bootstrap}}
    {{form.descricao | bootstrap}}
    {{form.especificacoes | bootstrap}}
    {{form.preco | bootstrap}}
    {{form.percentual_desconto | bootstrap}}
    {{form.quantidade_estoque | bootstrap}}
    {{form.imagem | bootstrap}}

    <input type="submit" class="btn btn-success" value="Enviar">
</form>
</div>
{% endblock %}

horizon/ecommerce/templates/ecommerce/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Carrinho{% endblock %}

{% block content %}
		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
                        <div class="cart-page-inner">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Produto</th>
                                            <th>Preço</th>
                                            <th>Quantidade</th>
                                            <th>Cor</th>
                                            <th>Remover</th>
                                        </tr>
                                    </thead>
									{% for item in carrinho %}										
										<tbody class="align-middle">
											<tr class="carttr">
												<td style="vertical-align: middle;">
													<div class="img">
														<a href="/detalhesproduto/{{item.produto.id}}"><img class="imgcart" src="{{item.produto.imagem.url}}" alt="Image"></a>
														<p>{{item.produto.nome}}</p>
													</div>
												</td>
												<td style="vertical-align: middle;">R$ {{item.produto.preco}}</td>
												<td style="vertical-align: middle;">
													<div class="row">
														<a href="/subtraiitemcarrinho/{{item.id}}" class="margembtn"><i class="fa fa-minus"></i></a>
														<input class= "inputcart" type="text" value="{{item.quantidade}}" style="text-align: center;" disabled="">
														<a href="/acrescentaitemcarrinho/{{item.id}}" class="margembtn"><i class="fa fa-plus"></i></a>

													</div>
												</td>
												<td style="vertical-align: middle;">{{item.cor.cor}}</td>
												<td style="vertical-align: middle;"><span><a href="/deletaitemdocarrinho/{{item.id}}"><i style="color: rgb(84, 83, 83);" class="fas fa-trash fa-2x"></i></a></span></td>
											</tr>
										</tbody>
									{% endfor %}
                                </table>
							{% if vazio == True %}
								<h3 style="text-align: center;margin-top: 3rem;">Seu carrinho está vazio</h3>
							{% endif %}
                            </div>
                        </div>

					</div>
					<br>
					<!-- Order Details -->
					{% if vazio != True %}
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Itens do Carrinho</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">
								<div><strong>PRODUTO</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
								{% for produto in produtos %}
									
									<div class="order-col">
										<div>{{produto.0}}x {{produto.1}}</div>
										<div>R$ {{produto.2}}</div>
									</div>
								{% endfor %}
							</div>
							<!--<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>-->
                            <hr>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
								<div><strong class="order-total">${{total}}</strong></div>
							</div>
						</div>
						<a href="/subtotal" class="primary-btn order-submit">Finalizar Pedido</a>
					</div>
					{% endif %}
					<!-- /Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
    {% endblock %}

horizon/ecommerce/templates/ecommerce/editacliente.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Editar Cliente{% endblock %}

{% block content %}
<div class="col-md-8 container">
<form method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label  " for="nome">Nome</label>
        <div class=" ">
            <input type="text" name="nome" maxlength="255" class=" form-control" required="" id="id_nome" value="{{nome}}">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label  " for="sobrenome">Sobrenome</label>
        <div class=" ">
            <input type="text" name="sobrenome" maxlength="255" class=" form-control" required="" id="id_sobrenome" value="{{sobrenome}}">
        </div>
    </div>
    {{form.endereco | bootstrap}}
    {{form.numero | bootstrap}}
    {{form.complemento | bootstrap}}
    {{form.cep | bootstrap}}
    {{form.telefone | bootstrap}}
    {{form.rg | bootstrap}}
    {{form.cpf | bootstrap}}
    {{form.sexo | bootstrap}}
    {{form.idade | bootstrap}}
  

    <input type="submit" class="btn btn-success" value="Enviar">
</form>
</div>
{% endblock %}

horizon/ecommerce/templates/ecommerce/exibelistadedesejos.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Carrinho{% endblock %}

{% block content %}
		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
                        <div class="cart-page-inner">
                            <h3 style="text-transform: uppercase">Lista de desejos</h3>
                            
                            <!-- store products -->
                            <div class="row">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th>Produto</th>
                                            <th>Preço</th>
                                            <th>Remover</th>
                                        </tr>
                                    </thead>
									{% for item in lista %}										
										<tbody class="align-middle">
											<tr class="carttr">
												<td style="vertical-align: middle;">
													<div class="img">
														<a href="/detalhesproduto/{{item.produto.id}}"><img class="imgcart" src="{{item.produto.imagem.url}}" alt="Image"></a>
														<p>{{item.produto.nome}}</p>
													</div>
												</td>
												<td style="vertical-align: middle;">R$ {{item.produto.preco}}</td>
												<td style="vertical-align: middle;"><span><a href="/removelistadedesejos/{{item.id}}"><i style="color: rgb(84, 83, 83);" class="fas fa-trash fa-2x"></i></a></span></td>
											</tr>
										</tbody>
									{% endfor %}
                                </table>
							{% if vazio == True %}
								<h3 style="text-align: center;margin-top: 3rem;">Sua lista está vazia</h3>
							{% endif %}
                            </div>
                        </div>

					</div>
					<br>
					<!-- Order Details -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
    {% endblock %}

horizon/ecommerce/templates/ecommerce/loja.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Horizon{% endblock %}

{% block content %}
<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Categorias</h3>
                            {% for categoria in categorias %}
                                <div class="checkbox-filter">
                                    <div class="input-checkbox">
                                        <label for="category-1">
                                            <span></span>
                                            <a href="/loja/{{categoria.id}}">{{categoria}}</a> 
                                        </label>
                                    </div>
                                </div>
                            {% endfor %}
						</div>
						<!-- /aside Widget -->

					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
                        <h3 style="text-transform: uppercase">{{categoria_a_ser_buscada}}</h3>
                        <hr>
						<!-- store products -->
						<div class="row">

							<!-- product -->
                            {% for produto in produtos %}
							<div class="col-md-4 col-xs-6">
                                <div class="product">
                                    <div class="product-img">
                                        <img src="{{produto.imagem.url}}" alt="">
                                        <div class="product-label">
                                            {% if produto.percentual_desconto > 0 %}
                                                <span class="sale">{{produto.percentual_desconto}}%</span>
                                            {% endif %}
                                                <span class="new">NEW</span>
                                        </div>
                                    </div>
                                    <div class="product-body">
                                        <p class="product-category">{{produto.categoria}}</p>
                                        <h3 class="product-name"><a href="/detalhesproduto/{{produto.id}}">{{produto.nome}}</a></h3>
                                        {% if produto.percentual_desconto > 0 %}
                                            <h4 class="product-price">R${{produto.preco_desconto}} <del class="product-old-price">R$ {{produto.preco}}</del></h4>
                                        {% else %}
                                        <h4 class="product-price">R$ {{produto.preco}}</h4>
                                        {% endif%}
                                        <div class="product-rating">
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                            <i class="fa fa-star"></i>
                                        </div>
                                        <div class="product-btns">
                                            <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                                        </div>
                                    </div>
                                    <div class="add-to-cart">
                                        <form action="/detalhesproduto/{{produto.id}}">
                                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i>COMPRAR</button>
                                        </form>
                                    </div>
                                </div>
							</div>
                            {% endfor %}
							<!-- /product -->
						</div>
						<!-- /store products -->

                        
						<!-- store bottom filter -->
                        <!--
						<div class="store-filter clearfix">
							<span class="store-qty"></span>
							<ul class="store-pagination">
								<li class="active">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
							</ul>
						</div>
                        -->
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% endblock %}

horizon/ecommerce/templates/ecommerce/vendafinalizada.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap %}
{% block title %}Horizon{% endblock %}

{% block content %}
    <h1 class="texto-sucesso">Sua venda foi finalizada com sucesso!</h1>
{% endblock %}